name: bci_donation_admin
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^3.1.2
  url_launcher: ^6.2.6

  flutter_easyloading: ^3.0.5
  flutter_html: ^2.2.1
  dio: ^5.1.1
  dartz: ^0.10.1
  json_annotation: ^4.5.0
  json_serializable: ^6.3.1
  rxdart: ^0.27.3
  shared_preferences: ^2.0.12
  intl: ^0.18.0
  fluttertoast: ^8.0.8
  flutter_bloc: ^8.1.2
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/